pub const VERSION: &str = env!("CARGO_PKG_VERSION");

pub mod changes;
pub mod config;
pub mod counters;
pub mod emit;
pub mod error;
pub mod exec;
pub mod git;
pub mod globs;
pub mod graph;
pub mod ids;
pub mod lock;
pub mod model;
pub mod overlay;
pub mod payload;
pub mod semantic;
pub mod span;
pub mod state;
pub mod suggest;
pub mod syntax;
pub mod workspace;
